[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "sed -i 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list",
    "echo \"deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted universe multiverse\" >> /etc/apt/sources.list",
    "echo \"deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted universe multiverse\" >> /etc/apt/sources.list",
    "apt-get update",
    "apt-get install --assume-yes libgtk-3-dev:arm64 libayatana-appindicator3-dev:arm64 libxdo-dev:arm64"
]