[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture aarch64",
    "apt-get update",
    "apt-get install --assume-yes libgtk-3-dev:arm64 libayatana-appindicator3-dev:arm64 libxdo-dev:arm64"
]